trigger: none

name: MacTimersBuildNative_$(Rev:.r)

jobs:
- job: BuildRunLoopTimerPrioritized
  displayName: 'Build RunLoopTimerPrioritized'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build RunLoopTimerPrioritized'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c RunLoopTimerPrioritized.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o RunLoopTimerPrioritized.dylib RunLoopTimerPrioritized.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish RunLoopTimerPrioritized'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/RunLoopTimerPrioritized.dylib'
      artifactName: 'RunLoopTimerPrioritized.dylib'
      artifactType: pipeline
- job: BuildRunLoopTimer
  displayName: 'Build RunLoopTimer'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build RunLoopTimer'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c RunLoopTimer.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o RunLoopTimer.dylib RunLoopTimer.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish RunLoopTimer'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/RunLoopTimer.dylib'
      artifactName: 'RunLoopTimer.dylib'
      artifactType: pipeline