trigger: none

name: MacTimersBuildNative_$(Rev:.r)

jobs:
- job: BuildRunLoopTimerPrioritized
  displayName: 'Build RunLoopTimerPrioritized'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build RunLoopTimerPrioritized'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c RunLoopTimerPrioritized.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o RunLoopTimerPrioritized.dylib RunLoopTimerPrioritized.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish RunLoopTimerPrioritized'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/RunLoopTimerPrioritized.dylib'
      artifactName: 'RunLoopTimerPrioritized.dylib'
      artifactType: pipeline
- job: BuildRunLoopTimer
  displayName: 'Build RunLoopTimer'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build RunLoopTimer'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c RunLoopTimer.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o RunLoopTimer.dylib RunLoopTimer.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish RunLoopTimer'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/RunLoopTimer.dylib'
      artifactName: 'RunLoopTimer.dylib'
      artifactType: pipeline
- job: BuildRunLoopTimerPrioritizedWithTolerance
  displayName: 'Build RunLoopTimerPrioritizedWithTolerance'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build RunLoopTimerPrioritizedWithTolerance'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c RunLoopTimerPrioritizedWithTolerance.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o RunLoopTimerPrioritizedWithTolerance.dylib RunLoopTimerPrioritizedWithTolerance.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish RunLoopTimerPrioritizedWithTolerance'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/RunLoopTimerPrioritizedWithTolerance.dylib'
      artifactName: 'RunLoopTimerPrioritizedWithTolerance.dylib'
      artifactType: pipeline
- job: BuildInfiniteLoopTimerWithNanosleep
  displayName: 'Build InfiniteLoopTimerWithNanosleep'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build InfiniteLoopTimerWithNanosleep'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c InfiniteLoopTimerWithNanosleep.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o InfiniteLoopTimerWithNanosleep.dylib InfiniteLoopTimerWithNanosleep.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish InfiniteLoopTimerWithNanosleep'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/InfiniteLoopTimerWithNanosleep.dylib'
      artifactName: 'InfiniteLoopTimerWithNanosleep.dylib'
      artifactType: pipeline
- job: BuildInfiniteLoopTimerWithNanosleepPrioritized
  displayName: 'Build InfiniteLoopTimerWithNanosleepPrioritized'
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build InfiniteLoopTimerWithNanosleepPrioritized'
    inputs:
      targetType: 'inline'
      script: |
        cd Resources/TgRl/MacTimers/Native
        gcc -c InfiniteLoopTimerWithNanosleepPrioritized.c
        gcc -shared -framework CoreServices -framework CoreFoundation -o InfiniteLoopTimerWithNanosleepPrioritized.dylib InfiniteLoopTimerWithNanosleepPrioritized.o
  - task: PublishPipelineArtifact@1
    displayName: 'Publish InfiniteLoopTimerWithNanosleepPrioritized'
    inputs:
      targetPath: 'Resources/TgRl/MacTimers/Native/InfiniteLoopTimerWithNanosleepPrioritized.dylib'
      artifactName: 'InfiniteLoopTimerWithNanosleepPrioritized.dylib'
      artifactType: pipeline